export enum RouterPath {
  authorization = '/subpackages/login/authorization/authorization',
  userPolicy = '/subpackages/login/userPolicy/userPolicy',
  home = '/pages/index/index',
  mine = '/pages/mine/mine',
  publish = '/pages/publish/publish',
  product = '/pages/product/product/product',
  information = '/pages/information/information/information',
  productDetail = '/subpackages/productManage/productDetail/productDetail',
  publishProduct = '/subpackages/productManage/publishProduct/publishProduct',
  commentList = '/subpackages/productManage/CommentList/CommentList',
  editRichContent = '/subpackages/editRichContent/editRichContent',
  publishInformation = '/subpackages/informationManage/publishInformation/publishInformation',
  informationDetail = '/subpackages/informationManage/informationDetail/informationDetail',
  authentication = '/subpackages/authentication/authentication',
  mineProduct = '/subpackages/mineProduct/mineProduct',
  homeSearch = '/subpackages/homeSearch/homeSearch',
  message = '/subpackages/message/message',
  accountRecharge = '/subpackages/account/accountRecharge/accountRecharge',
  accountWithdrawal = '/subpackages/account/accountWithdrawal/accountWithdrawal',
  productAttention = '/subpackages/personal/productAttention/productAttention',
  informationAttention = '/subpackages/personal/informationAttention/informationAttention',
  personalProductManage = '/subpackages/personal/personalProductManage/personalProductManage',
  personalInformationManage = '/subpackages/personal/personalInformationManage/personalInformationManage',
  mySelling = '/subpackages/personal/mySelling/mySelling',
  mySellingComment = '/subpackages/personal/mySellingComment/mySellingComment',
  payment = '/subpackages/payment/payment',
  myBuy = '/subpackages/personal/myBuy/myBuy',
  myBuyComment = '/subpackages/personal/myBuyComment/myBuyComment',
  applyRefund = '/subpackages/personal/applyRefund/applyRefund',
}

export const TabBarPageRouter = {
  Home: '/pages/index/index',
  Product: '/pages/product/product/product',
  Information: '/pages/information/information/information',
  Mine: '/pages/mine/mine',
};
